# 原始点云
raw_lidar_topic_name: /lidar_points

# 聚类并根据形状过滤后的锥桶质心坐标
cones_centroid_topic_name: /perception/cones_centroid

# 去除地面后的点云
filter_cones_topic_name: /perception/filter_cones

# 提取的地面点云
filter_ground_topic_name: /perception/filter_ground

# 聚类后的锥桶点云
cluster_cones_topic_name: /perception/cluster_cones

# 点云过滤距离阈值 (m)
MinRange: 0.5
MaxRange: 16  # 10
Min_x: 0
Max_z: 0.5

# 聚类参数
Cluster_Tolerance: 0.5
MinClusterSize: 5     # 5
MaxClusterSize: 1000  # 1000

# 聚类过滤阈值 (m)
Max_bound_x: 0.5
Max_bound_y: 0.5
Min_bound_z: -0.08
Max_bound_z: 0.6   # 0.6
max_centroid_height_: 0.4   # 0.4

node_rate: 15   # [Herz]
