set(_CATKIN_CURRENT_PACKAGE "estimationState")
set(estimationState_VERSION "1.0.0")
set(estimationState_MAINTAINER "chentairan <tairanchen@bitfsd.cn>")
set(estimationState_PACKAGE_FORMAT "2")
set(estimationState_BUILD_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "fsd_common_msgs" "coordSystem")
set(estimationState_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "fsd_common_msgs" "coordSystem")
set(estimationState_BUILDTOOL_DEPENDS "catkin")
set(estimationState_BUILDTOOL_EXPORT_DEPENDS )
set(estimationState_EXEC_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "fsd_common_msgs" "coordSystem")
set(estimationState_RUN_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "fsd_common_msgs" "coordSystem")
set(estimationState_TEST_DEPENDS )
set(estimationState_DOC_DEPENDS )
set(estimationState_URL_WEBSITE "")
set(estimationState_URL_BUGTRACKER "")
set(estimationState_URL_REPOSITORY "")
set(estimationState_DEPRECATED "")