set(_CATKIN_CURRENT_PACKAGE "daheng")
set(daheng_VERSION "0.0.0")
set(daheng_MAINTAINER "shawn <shawn@todo.todo>")
set(daheng_PACKAGE_FORMAT "2")
set(daheng_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "opencv2")
set(daheng_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy")
set(daheng_BUILDTOOL_DEPENDS "catkin")
set(daheng_BUILDTOOL_EXPORT_DEPENDS )
set(daheng_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "opencv2")
set(daheng_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "opencv2")
set(daheng_TEST_DEPENDS )
set(daheng_DOC_DEPENDS )
set(daheng_URL_WEBSITE "")
set(daheng_URL_BUGTRACKER "")
set(daheng_URL_REPOSITORY "")
set(daheng_DEPRECATED "")