#Subscriber
car_state_topic_name : /estimation/slam/state
skidpad_track_topic_name : /transform_matrix

#Publisher
control_command_topic_name: /control/pure_pursuit/control_command
trajectory_path_topic_name: /path/trajectory
target_path_topic_name: /path/target
predict_path_topic_name: /path/predict

# MPC params:
weight:
  x: 1.5
  y: 1.5
  yaw: 8
  lateral_error: 1
  yaw_error: 0
  v: 0.4
  steering_angle: 4
  throttle: 10
  steering_rate: 2000
  throttle_rate: 10
  desire_vel: 20

# Pure Pursuit params:
desire_vel: 10

car_length: 1.88

look_ahead: 10

# Track params:
interval: 0.05

forward_distance: 15.0

circle_radius: 9.125

max_lat_acc: 3.0



# other params:
N: 40

dt: 0.02

initial_velocity: 2

mission: skidpad          # [trackdrive, skidpad, acceleration]

controller: pure_pursuit  # [mpc, pure_pursuit]

simulation: true

node_rate: 20   # [Herz]

