set(_CATKIN_CURRENT_PACKAGE "can_interaction")
set(can_interaction_VERSION "1.0.0")
set(can_interaction_MAINTAINER "chentairan <tairanchen@bitfsd.cn>")
set(can_interaction_PACKAGE_FORMAT "2")
set(can_interaction_BUILD_DEPENDS "fsd_common_msgs" "roscpp" "std_msgs" "geometry_msgs")
set(can_interaction_BUILD_EXPORT_DEPENDS "fsd_common_msgs" "roscpp" "std_msgs" "geometry_msgs")
set(can_interaction_BUILDTOOL_DEPENDS "catkin")
set(can_interaction_BUILDTOOL_EXPORT_DEPENDS )
set(can_interaction_EXEC_DEPENDS "fsd_common_msgs" "roscpp" "std_msgs" "geometry_msgs")
set(can_interaction_RUN_DEPENDS "fsd_common_msgs" "roscpp" "std_msgs" "geometry_msgs")
set(can_interaction_TEST_DEPENDS )
set(can_interaction_DOC_DEPENDS )
set(can_interaction_URL_WEBSITE "")
set(can_interaction_URL_BUGTRACKER "")
set(can_interaction_URL_REPOSITORY "")
set(can_interaction_DEPRECATED "")