set(_CATKIN_CURRENT_PACKAGE "fusion")
set(fusion_VERSION "1.0.0")
set(fusion_MAINTAINER "ShawnPan <312855417@qq.com>")
set(fusion_PACKAGE_FORMAT "2")
set(fusion_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "opencv2" "message_filters" "message_generation" "std_msgs" "geometry_msgs" "pcl_conversions" "pcl_msgs" "pcl_ros")
set(fusion_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "message_filters" "message_generation" "std_msgs" "geometry_msgs" "pcl_conversions" "pcl_msgs" "pcl_ros")
set(fusion_BUILDTOOL_DEPENDS "catkin" "catkin")
set(fusion_BUILDTOOL_EXPORT_DEPENDS )
set(fusion_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "opencv2" "message_filters" "message_runtime" "std_msgs" "geometry_msgs" "pcl_conversions" "pcl_msgs" "pcl_ros")
set(fusion_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "rospy" "opencv2" "message_filters" "message_runtime" "std_msgs" "geometry_msgs" "pcl_conversions" "pcl_msgs" "pcl_ros" "message_generation")
set(fusion_TEST_DEPENDS )
set(fusion_DOC_DEPENDS )
set(fusion_URL_WEBSITE "")
set(fusion_URL_BUGTRACKER "")
set(fusion_URL_REPOSITORY "")
set(fusion_DEPRECATED "")