// Generated by gencpp from file lidar_cluster/ClusterCone.msg
// DO NOT EDIT!


#ifndef LIDAR_CLUSTER_MESSAGE_CLUSTERCONE_H
#define LIDAR_CLUSTER_MESSAGE_CLUSTERCONE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace lidar_cluster
{
template <class ContainerAllocator>
struct ClusterCone_
{
  typedef ClusterCone_<ContainerAllocator> Type;

  ClusterCone_()
    : id(0)
    , xmax(0.0)
    , ymax(0.0)
    , zmax(0.0)
    , xmin(0.0)
    , ymin(0.0)
    , zmin(0.0)
    , pointcloud()  {
    }
  ClusterCone_(const ContainerAllocator& _alloc)
    : id(0)
    , xmax(0.0)
    , ymax(0.0)
    , zmax(0.0)
    , xmin(0.0)
    , ymin(0.0)
    , zmin(0.0)
    , pointcloud(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef double _xmax_type;
  _xmax_type xmax;

   typedef double _ymax_type;
  _ymax_type ymax;

   typedef double _zmax_type;
  _zmax_type zmax;

   typedef double _xmin_type;
  _xmin_type xmin;

   typedef double _ymin_type;
  _ymin_type ymin;

   typedef double _zmin_type;
  _zmin_type zmin;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_type;
  _pointcloud_type pointcloud;





  typedef boost::shared_ptr< ::lidar_cluster::ClusterCone_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_cluster::ClusterCone_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterCone_

typedef ::lidar_cluster::ClusterCone_<std::allocator<void> > ClusterCone;

typedef boost::shared_ptr< ::lidar_cluster::ClusterCone > ClusterConePtr;
typedef boost::shared_ptr< ::lidar_cluster::ClusterCone const> ClusterConeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_cluster::ClusterCone_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_cluster::ClusterCone_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_cluster::ClusterCone_<ContainerAllocator1> & lhs, const ::lidar_cluster::ClusterCone_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.xmax == rhs.xmax &&
    lhs.ymax == rhs.ymax &&
    lhs.zmax == rhs.zmax &&
    lhs.xmin == rhs.xmin &&
    lhs.ymin == rhs.ymin &&
    lhs.zmin == rhs.zmin &&
    lhs.pointcloud == rhs.pointcloud;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_cluster::ClusterCone_<ContainerAllocator1> & lhs, const ::lidar_cluster::ClusterCone_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_cluster

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_cluster::ClusterCone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_cluster::ClusterCone_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_cluster::ClusterCone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_cluster::ClusterCone_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_cluster::ClusterCone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_cluster::ClusterCone_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_cluster::ClusterCone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "175022e058f9e9b8f7839276903b1b47";
  }

  static const char* value(const ::lidar_cluster::ClusterCone_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x175022e058f9e9b8ULL;
  static const uint64_t static_value2 = 0xf7839276903b1b47ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_cluster::ClusterCone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_cluster/ClusterCone";
  }

  static const char* value(const ::lidar_cluster::ClusterCone_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_cluster::ClusterCone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"float64 xmax\n"
"float64 ymax\n"
"float64 zmax\n"
"float64 xmin\n"
"float64 ymin\n"
"float64 zmin\n"
"sensor_msgs/PointCloud2 pointcloud\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::lidar_cluster::ClusterCone_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_cluster::ClusterCone_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.xmax);
      stream.next(m.ymax);
      stream.next(m.zmax);
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.zmin);
      stream.next(m.pointcloud);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterCone_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_cluster::ClusterCone_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_cluster::ClusterCone_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "xmax: ";
    Printer<double>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<double>::stream(s, indent + "  ", v.ymax);
    s << indent << "zmax: ";
    Printer<double>::stream(s, indent + "  ", v.zmax);
    s << indent << "xmin: ";
    Printer<double>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<double>::stream(s, indent + "  ", v.ymin);
    s << indent << "zmin: ";
    Printer<double>::stream(s, indent + "  ", v.zmin);
    s << indent << "pointcloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_CLUSTER_MESSAGE_CLUSTERCONE_H
