set(_CATKIN_CURRENT_PACKAGE "lidar_check")
set(lidar_check_VERSION "0.0.0")
set(lidar_check_MAINTAINER "shawn <shawn@todo.todo>")
set(lidar_check_PACKAGE_FORMAT "2")
set(lidar_check_BUILD_DEPENDS "roscpp" "rsopy" "sensor_msgs" "std_msgs")
set(lidar_check_BUILD_EXPORT_DEPENDS "roscpp" "rsopy" "sensor_msgs" "std_msgs")
set(lidar_check_BUILDTOOL_DEPENDS "catkin")
set(lidar_check_BUILDTOOL_EXPORT_DEPENDS )
set(lidar_check_EXEC_DEPENDS "roscpp" "rsopy" "sensor_msgs" "std_msgs")
set(lidar_check_RUN_DEPENDS "roscpp" "rsopy" "sensor_msgs" "std_msgs")
set(lidar_check_TEST_DEPENDS )
set(lidar_check_DOC_DEPENDS )
set(lidar_check_URL_WEBSITE "")
set(lidar_check_URL_BUGTRACKER "")
set(lidar_check_URL_REPOSITORY "")
set(lidar_check_DEPRECATED "")