set(_CATKIN_CURRENT_PACKAGE "coordSystem")
set(coordSystem_VERSION "1.0.0")
set(coordSystem_MAINTAINER "chentairan <tairanchen@bitfsd.cn>")
set(coordSystem_PACKAGE_FORMAT "2")
set(coordSystem_BUILD_DEPENDS "message_generation" "roscpp" "std_msgs" "geometry_msgs")
set(coordSystem_BUILD_EXPORT_DEPENDS "message_generation" "roscpp" "std_msgs" "geometry_msgs")
set(coordSystem_BUILDTOOL_DEPENDS "catkin")
set(coordSystem_BUILDTOOL_EXPORT_DEPENDS )
set(coordSystem_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs")
set(coordSystem_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "message_generation")
set(coordSystem_TEST_DEPENDS )
set(coordSystem_DOC_DEPENDS )
set(coordSystem_URL_WEBSITE "")
set(coordSystem_URL_BUGTRACKER "")
set(coordSystem_URL_REPOSITORY "")
set(coordSystem_DEPRECATED "")