set(_CATKIN_CURRENT_PACKAGE "imu_load")
set(imu_load_VERSION "1.0.0")
set(imu_load_MAINTAINER "chentairan <tairanchen@bitfsd.cn>")
set(imu_load_PACKAGE_FORMAT "2")
set(imu_load_BUILD_DEPENDS "message_generation" "roscpp" "std_msgs" "geometry_msgs")
set(imu_load_BUILD_EXPORT_DEPENDS "message_generation" "roscpp" "std_msgs" "geometry_msgs")
set(imu_load_BUILDTOOL_DEPENDS "catkin")
set(imu_load_BUILDTOOL_EXPORT_DEPENDS )
set(imu_load_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs")
set(imu_load_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs" "geometry_msgs" "message_generation")
set(imu_load_TEST_DEPENDS )
set(imu_load_DOC_DEPENDS )
set(imu_load_URL_WEBSITE "")
set(imu_load_URL_BUGTRACKER "")
set(imu_load_URL_REPOSITORY "")
set(imu_load_DEPRECATED "")