set(_CATKIN_CURRENT_PACKAGE "lidar_cluster")
set(lidar_cluster_VERSION "0.0.0")
set(lidar_cluster_MAINTAINER "chentairan <killasipilin@gmail.com>")
set(lidar_cluster_PACKAGE_FORMAT "2")
set(lidar_cluster_BUILD_DEPENDS "visualization_msgs" "message_generation" "fsd_common_msgs" "roscpp" "std_msgs" "geometry_msgs" "pcl_conversions" "pcl_msgs" "pcl_ros")
set(lidar_cluster_BUILD_EXPORT_DEPENDS "visualization_msgs" "message_generation" "fsd_common_msgs" "roscpp" "std_msgs" "geometry_msgs" "pcl_conversions" "pcl_msgs" "pcl_ros")
set(lidar_cluster_BUILDTOOL_DEPENDS "catkin")
set(lidar_cluster_BUILDTOOL_EXPORT_DEPENDS )
set(lidar_cluster_EXEC_DEPENDS "visualization_msgs" "message_runtime" "fsd_common_msgs" "roscpp" "std_msgs" "geometry_msgs" "pcl_conversions" "pcl_msgs" "pcl_ros")
set(lidar_cluster_RUN_DEPENDS "visualization_msgs" "message_runtime" "fsd_common_msgs" "roscpp" "std_msgs" "geometry_msgs" "pcl_conversions" "pcl_msgs" "pcl_ros" "message_generation")
set(lidar_cluster_TEST_DEPENDS )
set(lidar_cluster_DOC_DEPENDS )
set(lidar_cluster_URL_WEBSITE "")
set(lidar_cluster_URL_BUGTRACKER "")
set(lidar_cluster_URL_REPOSITORY "")
set(lidar_cluster_DEPRECATED "")